[package]
name = "boruna-orchestrator"
version.workspace = true
edition.workspace = true

[[bin]]
name = "boruna-orch"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10"
boruna-effect = { path = "../crates/llm-effect" }

[dev-dependencies]
tempfile = "3"
